### ISSUE TITLE
Missing the mutating webhook leads to broken nginx ingress controller

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardener-extension-provider-aws#134]
**How to categorize this issue?**
/area control-plane
/platform aws

**What happened**:
1. Created a cluster with enabled nginx-ingress addon
2. I assume the webhook gardener-extension-provider-aws was down/unreachable in that moment
3. The nginx `ConfigMap` in the shoot's `kube-system` ns was created with `use-proxy-protocol: "false"` (obviously the default from https://github.com/gardener/gardener/blob/master/charts/shoot-addons/charts/nginx-ingress/values.yaml#L15)
4. However the LBs in AWS are configured with proxy protocol enabled
5. As a result, all requests via LB to the nginx ingress respond with `HTTP 400` as nginx didn't understand the proxy protocol.

**What you expected to happen**:
Nginx ingress to work.

**Anything else we need to know?**:
I think part of the problem is the gardener-extension-provider-aws webhook's `failurePolicy: Ignore`.
Maybe the webhook configuration could be more selective so that `failurePolicy: Fail` could be used instead.

**Comment by rfranzke** [comment]
/assign @tim-ebert @rfranzke 

We have the suspicion that this has been introduced as part of https://github.com/gardener/gardener-resource-manager/pull/47. The extension webhook concept relies on the assumption that the GRM is always sending an UPDATE request for the resources even if there is no difference compared to the actual deployed version.

However, with the mentioned improvement this has changed, i.e., the GRM is now "smart" and only sends an UPDATE if it detects a change.
We are currently validating this. If it turns out to be correct then we'll make the GRM to always send the UPDATE for resources managed in the shoot (the communication is happening cluster-internally anyways, so it should be OK).

/in-progress
