### ISSUE TITLE
Allow reuse of ALB

### ISSUE THREAD

**Issue by rauizab** [gardener/gardener-extension-provider-aws#15]
**What would you like to be added**:
All entry points should reuse and existing alb, by adding a new target groups; instead that 2 elb per cluster as it is being done now.

**Why is this needed**:
We are going to have several clusters working together and we need access to the api and the ingress controller. At the moment we have (2 * number of clusters) ELBs.
It would be ideal if we can define that all entry points reuse and existing alb, by adding a new target group.
We would reduce the entry points to our system to a single one; improving security, making easier to get logs, reducing costs...

**Comment by rfranzke** [comment]
Hello @rauizab 

>  instead that 2 elb per cluster as it is being done now.

Are you talking about the load balancers for the vpn-shoot and nginx-ingress controller?
Regarding the vpn-shoot: @mvladev is working on optimizing this so that there is not even a load balancer in your shoot cluster in the first place. So, eventually, this LB will disappear.
Regarding the nginx-ingress: This addon is just for experimental/trial usage but not recommended for production or anything else. You can disable it in the Shoot and deploy your own nginx-ingress - then you can also completely control how it is exposed (ELB/ALB/NLB/...).

/close
