### ISSUE TITLE
allow customizing instance metadata options

### ISSUE THREAD

**Issue by tareksha** [gardener/gardener-extension-provider-aws#468]
/area control-plane
/kind enhancement
/platform aws

**What would you like to be added**:

I would like to have the ability to customize ec2 instance metadata options at worker level. Most importantly I want to modify the option `HttpPutResponseHopLimit` which is very useful for using the EC2 IAM Roles feature from containerized applications on top of ec2 instances:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html
The security-credentials endpoint limits the number of hops at IP level to 1 by default. This makes it inaccessible from inside containers because their network traffic goes through an additional hop. To make the endpoint accessible from inside containerized applications the metadata option `HttpPutResponseHopLimit` must be changed to 2 (or higher).

I suggest adding a new section to `WorkerConfig`:
```yaml
apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
kind: WorkerConfig
...
instanceMetadataOptions:
  httpPutResponseHopLimit: 2
```

Full list of options:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceMetadataOptions.html

**Possible alternative**

If we do not want a full-fledged feature for customizing the options maybe we can change the hop limit to 2 by default. The instances are created for the purpose of running containerized applications anyway. EKS did this:
https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-supports-ec2-instance-metadata-service-v2/
> Now, newly launched and any updated EKS managed node groups will be configured with a metadata token response hop limit set to 2.

**Why is this needed**:

Allow using IAM Roles for EC2 instances in gardener clusters conveniently.

**Comment by etiennnr** [comment]
Related old PR : https://github.com/gardener/machine-controller-manager-provider-aws/pull/61

**Comment by shenningz** [comment]
We also require this feature for our application which currently relies on [AWS IMDSv1](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html). Since v1 may be [vulnerable to certain attacks](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/), AWS is pushing their partners and customers towards IMDSv2. To address these security concerns, we really would like to migrate our application to v2. However, the token-based access method in IMDSv2 does not work with a hop limit of 1 in containers, so this is a showstopper right now.
