### ISSUE TITLE
AWS: traffic to Service Endpoints is routed externally

### ISSUE THREAD

**Issue by henrikhempelmann** [gardener/gardener-extension-provider-aws#607]
**How to categorize this issue?**

/area networking
/kind bug
/platform aws

**What happened**:
created a new cluster with VPC containing AWS Service Endpoint. Configured via

```
serviceEndpoints:
- s3
```

S3 traffic is routed externally via NAT GW - being charged for that :-(

**What you expected to happen**:
S3 traffic should be routed internally directly to this service endpoint

**How to reproduce it (as minimally and precisely as possible)**:
create new VPC with
```
serviceEndpoints:
- s3
```

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): 
- Extension version:
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: AWS
- Others:

**Comment by dkistner** [comment]
This can be most likely fixed by attaching the gateway endpoints to the respective route tables. This will result in a route that ensures that traffic to s3 (or DynamoDB) will be routed via the AWS backbone and does not go out through the internet gateway and then through the nat.

- https://docs.aws.amazon.com/vpc/latest/privatelink/gateway-endpoints.html
- https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html#associate-route-tables-s3
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_route_table_association
